spring.application.name=demoForGit
weather.api.key=286fed8293e53227d0ded46ad50cbf6f

# MariaDB configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/weather
spring.datasource.username=root
spring.datasource.password=2003
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
